config/routes.rb
require 'api'
Rails.application.routes.draw do
  devise_for :app_users, skip: [:sessions, :passwords, :registrations]
# root to: "home#index"
match  'blog' => 'website/home#blog', :via => :get
  get  '*a.txt', :to => 'website/errors#routing'


  namespace :api do
    namespace :v1 do
      devise_scope :app_user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      match 'service_categories' => 'service_categories#index', :via => :get
      match 'service_preferences' => 'service_preferences#create', :via => :post
      match 'service_preferences/send_ios_notification' => 'service_preferences#send_ios_notification', :via => :get
      match 'notifications' => 'notifications#create', :via => :post
      match 'get_notification' => 'notifications#fetch_notification', :via => :get
      match 'app_users' => 'app_users#create', :via => :post
      match 'update_user' => 'app_users#update_app_user', :via => :post
      match 'service_providers' => 'service_providers#get_service_providers', :via => :get
      match 'device_details' => 'device_tracker#add_devise_details', :via => :post
      match 'destroy_session' => 'device_tracker#destroy_session', :via => :post
      match 'get_preferences' => 'service_preferences#fetch_service_preferences', :via => :get
      match 'deselect_prference' => 'service_preferences#deselect_service_preference', :via => [:delete,:post]
      match 'get_states' => 'orders#get_states', :via => :get
      match 'get_cities' => 'orders#get_cities', :via => :get
      match 'primary_information' => "app_users#primary_information", :via => :get
      match 'cellphone_equipments' => "deals#cellphone_equipments", :via => :get
      match 'customisable_deals' => "deals#customisable_deals", :via => :get
      match 'customisable_deal_deatail' => "deals#customisable_deal_deatail", :via => :get
      match 'channel_customisable_deals' => "deals#channel_customisable_deals", :via => :get
      match 'cellphone_details' => "deals#cellphone_details", :via => :get
      match 'service_deal_config' => "deals#service_deal_config", :via => :get
      match 'password_complicated_setting' => "deals#password_complicated_setting", :via => :get
       match 'compare_deals' => "deals#compare_deals", :via => :get


      resources :dashboards do
        post 'dashboards' => 'dashboards#index'
      end
      resources :deals do
        get 'deals' => 'deals#index'
      end
      match 'app_user' => 'app_users#get_app_user', :via => :get
      match 'you_save' => 'app_users#you_save', :via => :get
      match 'service_preferences' => 'service_preferences#get_service_preferences', :via => :get
      match 'forget_password' => 'app_users#recover_password', :via => :post
      match 'comment_ratings' => 'comment_ratings#create', :via => :post
      match 'comment_ratings' => 'comment_ratings#index', :via => :get
      match 'referral_tracking' => 'referral_infos#create', :via => :post
      match 'get_category_deals' => 'dashboards#category_deals', :via => :get
      match 'subscribed_deals' => 'subscribe_deals#subscription_info', :via => :post
      match 'orders' => 'orders#create', :via => :post
      match 'get_orders' => 'orders#get_orders', :via => :get
      match 'my_orders' => 'orders#my_orders', :via => :get
      match 'get_order_address' => 'orders#get_order_address', :via => :get
      match 'get_gifts' => 'gifts#get_gifts', :via => :get
      match 'account_referrals' => 'account_referrals#create', :via => :post
      match 'referral_code' => 'app_users#my_referral_code', :via => :get
      match 'my_earnings' => 'app_users#referrals_and_gifts', :via => :get
      match 'cashout' => 'cashout_infos#create', :via => :post
      match 'refer_contact' => 'app_users#refer_contact', :via => :post
      match 'validate_business_name' => 'dashboards#validate_business_name', :via => :post
      match 'get_deal_channels' => 'deals#get_deal_channels', :via => :get
      match 'get_channel_details' => 'deals#get_channel_details', :via => :get
      match 'get_estimated_bandwidth' => 'deals#get_estimated_bandwidth', :via => :post
      match 'verify_user'=>"app_users#verify_user", :via => :get
      match 'deal_details'=>"deals#fetch_deal_details", :via => :get
      match 'dynamic_label_for_service_provider'=>"dashboards#dynamic_label_for_service_provider", :via => :get
      match 'get_rewards' => 'gifts#get_rewards', :via => :get
      resources :orders do
        collection do
          post :fetch_user_and_deal_details
          post :my_order_details
          post :validate_business_name
        end
      end

    end
  end

  #resources :service_categories do
  #  collection { post :import }
  #end
  get "/proxy_verify"=>"website/app_users#proxy_verify"
  match "/edit_addresses" => "website/app_users#edit_addresses", :via => [:post]
  match "/set_default_address" => "website/app_users#set_default_address", :via => [:post]
  match "/delete_address" => "website/app_users#delete_address", :via => [:post]
  match "/edit_or_change_service_preferences" => "api/v1/service_preferences#create", :via => :post
  get "/tnc" =>"website/home#tnc"
  get "/contact_us" =>"website/home#contact_us"
  get "/about_us" =>"website/home#about_us"
  get "/privacy_policy" =>"website/home#privacy_policy"

  #
  # if Socket.gethostname=="servicedlz-Virtual-Machine"
  # root to: "home#index"
  # else
  root to: "website/home#index"
  # end

  devise_for :users
  resources :users do
    member do
      get :edit_password
      get :unlock
      put :update_password
    end
    collection do
      get :reset_password
      post :set_reset_password
    end
  end
  get "/calculate_bandwidth" => "website/home#calculate_bandwidth"
  get "/get_deals_from_first_page" =>"website/home#get_deals_from_first_page"
  get '/get_user_addresses'=> "website/app_users#user_addresses"
  get '/get_business_user_addresses'=> "website/app_users#business_user_addresses"
  get "/extra_service_deal" => 'extra_services#extra_service_deal'

  get 'deals/get_service_providers'=>'deals#get_service_providers'
  get "/searchzip" => "deals#searchzip"
  get "/verify_email"=>"website/app_users#verify_email"
  resources :deals do
    post 'import', on: :collection
  end
  resources :service_categories do
    post 'import', on: :collection
  end
  resources :app_users
  resources :service_preferences
  resources :notifications
  resources :service_providers do
    post 'import', on: :collection
  end
  resources :advertisements
  #resources :comments
  #resources :ratings
  resources :bulk_notifications
  resources :comment_ratings
  resources :referral_infos
  resources :internet_service_preferences
  resources :cable_service_preferences
  resources :telephone_service_preferences
  resources :cellphone_service_preferences
  resources :bundle_service_preferences
  resources :subscribe_deals
  resources :trending_deals
  resources :zipcodes do
    post 'import', on: :collection
  end
  resources :orders
  resources :gifts
  resources :user_gifts
  resources :channels
  resources :channel_packages


  get 'service_dealz' => 'website/home#index'
  get 'service_deals' => 'website/home#index'
  get 'website' => 'website/home#index'
  namespace :website do
    resources :home do
      collection do
        get :deals
        get :compare_deals
        get :deal_details
        get :more_deal_details
        get :set_zipcode_and_usertype
        get :contact_us
        get :about_us
        get :our_providers
        get :coming_soon
        get :tnc
      end
    end

    resources :app_users do
      collection do
        get :check_user_email_ajax
        get :check_user_credential
        get :signout
        post :signin
        get :checkout
        get :profile
        get :order_history
        post :preferences
        get :order
        get :order_detail
        post :create_order
        post :contact_us
        get :forget_password
        get :edit_password
        post :update_password
        get :order_attributes
        get :order_extra_services
        get :order_equipment_data
        get :order_channel_packages
        get :order_cable_equipments
      end
    end
  end

  resources :referral_gift_amounts
  resources :service_provider_checklists do
    post 'import', on: :collection
  end
  resources :deal_equipments
  resources :deal_attributes
  resources :deal_extra_services
  resources :equipment_colors
  resources :cellphone_details
  resources :extra_services

  get  '*a', :to => 'website/errors#routing'


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController


	def index
		@deals = Deal.paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
    respond_to do |format|
      format.html
      #format.xls # { send_data @products.to_csv(col_sep: "\t") }
      format.csv {
        csv_string = CSV.generate do |csv|
          # header row

          csv <<
          [ "ID",
            "Service Category ID",
            "Service Provider ID",
            "Title",
            "State",
            "City",
            "Zip",
            "Price",
            "Upload Speed",
            "Download Speed",
            "Free Channels",
            "Premium Channels",
            "Data Plan",
            "Data Speed",
            "Domestic Call Minutes",
            "International Call Minutes",
            "Domestic Call Unlimited",
            "International Call Unlimited",
            "Bundle Combo",
            "Is Active",
            "URL",
            "Start Date",
            "End Date",
            "Short Description",
            "Detail Description",
            "Image",
            "Created At",
            "Updated At",
          ]

          # data rows
          Deal.all.order("id ASC").each do |deal|
            csv <<
            [ deal.id,
              deal.service_category_id,
              deal.service_provider_id,
              deal.title,
              deal.state,
              deal.city,
              deal.zip,
              deal.price,
              deal.upload_speed,
              deal.download_speed,
              deal.free_channels,
              deal.premium_channels,
              deal.data_plan,
              deal.data_speed,
              deal.domestic_call_minutes,
              deal.international_call_minutes,
              deal.domestic_call_unlimited,
              deal.international_call_unlimited,
              deal.bundle_combo,
              deal.is_active,
              deal.url,
              deal.start_date,
              deal.end_date,
              deal.short_description,
              deal.detail_description,
              deal.image.url,
              deal.created_at,
              deal.updated_at
            ]
          end
        end
        # send it to the browser
        send_data csv_string,
          :type => 'text/csv; charset=iso-8859-1; header=present',
          :disposition => "attachment; filename=deals.csv"
      }
    end
	end

	def new
    @deal = Deal.new
    @deal_internet = @deal.internet_deal_attributes.build
    @deal_internet.internet_equipments.build
    @deal_telephone = @deal.telephone_deal_attributes.build
    @deal_telephone.telephone_equipments.build
    @deal_cable = @deal.cable_deal_attributes.build
    @deal_cable.cable_equipments.build
    @deal_cellphone = @deal.cellphone_deal_attributes.build
    @deal_cellphone.cellphone_equipments.build
    @deal_bundle = @deal.bundle_deal_attributes.build
    @deal_bundle.bundle_equipments.build
    @deal.additional_offers.build
    @deal.deal_include_zipcodes.build
  end

  def get_service_providers
    #@ServiceProviders=ServiceProvider.select("id, name").where(service_category_name: params[:category])
    @ServiceProviders=ServiceProvider.select("id, name").where(service_category_id: params[:category])
    render :json => @ServiceProviders
  end

	def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        #send_notification
        format.html { redirect_to deals_path, :notice => 'You have successfully created a deal' }
        format.xml  { render :xml => @deal, :status => :created, :deal => @deal }
      else
        #raise @deal.errors.inspect
        format.html { render :action => "new" }
        format.json  { render :json => @deal.errors, :status => :unprocessable_entity }
      end
    end
	end
	def edit
  	@deal = Deal.find(params[:id])
  end
	def update
		@deal = Deal.find(params[:id])
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deals_path, notice: 'You have successfully updated a Deal.' }
        format.xml  { render :xml => @deal, :status => :created, :deal => @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @deal = Deal.find(params[:id])
    respond_to do |format|
          if @deal.destroy
            format.html { redirect_to deals_path, :notice => 'You have successfully removed a deal' }
            format.xml  { render :xml => @deal, :status => :created, :deal => @deal }
          end
    end
  end
  def import
    Deal.import(params[:file])
    redirect_to deals_path, :notice => "Successfully imported."
  end

	def searchzip
		zip = Zipcode.where("code like '#{params[:zip]}%' ").first
		#puts zip.to_yaml
		if zip
			render :json=>{
				:city => zip.city,
				:area => zip.area,
				:country => zip.country
			}
		end
	end

	private

  #def send_notification
  #  @app_user = AppUser.where("zip = ?",params[:deal][:zip])
  #  gcm = GCM.new("AIzaSyASkbVZHnrSGtqjruBalX0o0rQRA1dYU7w")
  #  @app_user.map do |a_user|
  #    registration_id = ["#{a_user.gcm_id}"]
      #message = "New deal for zip #{params[:deal][:zip]}.Visit Url : #{params[:deal][:url]}"
  #    gcm.send(registration_id, {data: {message: "New deal for zip #{params[:deal][:zip]}.Visit Url : #{params[:deal][:url]}"}})
  #  end
  #end

  def deal_params
    params.require(:deal).permit!
  end



end

app/views/deals/_additional_offer_fields.html.erb
<fieldset id="additional-offer">
   <h4>Additional Offer for zip areas</h4>
   <table class="form-data">
    <tr>
      <td valign="top">
        <%= f.label :title %>
        <%= f.text_field :title, :id=>'additional-offer-title' %>
      </td>
      <td>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </td>
    </tr>
    <tr>
      <td valign="top">
        <%= f.label :price %>
        <%= f.text_field :price %>
      </td>
      <td>
        <br/>
        <div><%= f.check_box :is_nationwide,:class=>'additional-offer-nationwide', :checked=>'checked' %> Is Nationwide? </div>
        <%= f.label 'Select Allowed Zipcodes:' %>
        <%= f.select :zipcode_ids, "",{id: "deal-include-zipcode",multiple: true,size: 10 } %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :start_date %>
        <%= f.text_field :start_date, :class=>'additional-offer-start-date' %>
      </td>
      <td>
        <%= f.label :end_date %>
        <%= f.text_field :end_date, :class=>'additional-offer-end-date' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :contract_period %>
        <%= f.select :contract_period , options_for_select([3,6,9,12])%>
      </td>
      <td>
        <div><%= f.check_box :is_active %> Is Active? </div>
      </td>
    </tr>
    <tr>
      <td>
        <%#= f.hidden_field :_destroy %>
        <%#= link_to "Remove", '#', class: "remove_fields" %>
      </td>
    </tr>
  </table>
</fieldset>

<script type="text/javascript">
  $(".additional-offer-nationwide").click(function(){
    if($(this).is(':checked')){
        $(".additional-offer-zipcode").prop("disabled",true);
      }else{
        $(".additional-offer-zipcode").prop("disabled",false);
      }
  });

$(function() {
  $('.additional-offer-start-date').each(function() {
    $(this).datepicker({ dateFormat: 'dd-mm-yy' });
  });
  $('.additional-offer-end-date').each(function() {
    $(this).datepicker({ dateFormat: 'dd-mm-yy' });
  });

});
// </script>

app/views/deals/_bundle_attribute.html.erb
<fieldset id="bundle-attributes" style="display:none;">
  <h4>Bundle Deal Attributes</h4>

  <%= f.label :bundle_combo %>
  <%= f.select :bundle_combo, options_for_select(['Internet,Telephone and Cable','Internet and Telephone','Internet and Cable','Telephone and Cable'].map{|o| [o,o] }) %>

  <div id="bundle-internet">
  <div>Downloads (mbps)<span class="mandat">*</span></div>
  <%= f.text_field :download, :id=>'bundle-internet-download' %>
  
  <%= f.label 'Upload (mbps)' %>
  <%= f.text_field :upload %>

  <%= f.label :data %>
  <%= f.text_field :data %>

  <%= f.label :static_ip %>
  <%= f.text_field :static_ip %>
  </div>

  <div id="bundle-telephone">
  <div>Domestic Call Minutes<span class="mandat">*</span></div>
  <div><input type='checkbox' id='bundle_domestic_unlimited'><span> Unlimited</span></div>
  <%= f.text_field :domestic_call_minutes, :id=>'bundle-telephone-domestic-call-minutes' %>

  <%= f.label :international_call_minutes %>
  <div><input type='checkbox' id='bundle_international_unlimited'><span> Unlimited</span></div>
  <%= f.text_field :international_call_minutes,:id=>'bundle-telephone-international-call-minutes' %>
  </div>

  <div id="bundle-cable">
  <div>Free channels<span class="mandat">*</span></div>
  <%= f.text_field :free_channels, :id=>'bundle-cable-free-channels' %>
  
  <%= f.label 'Free channels list (comma separated)' %>
  <%= f.text_field :free_channels_list %>

  <%= f.label :premium_channels %>
  <%= f.text_field :premium_channels %>

  <%= f.label 'Premium channels list (comma separated)' %>
  <%= f.text_field :premium_channels_list %>

  <%= f.label :hd_channels %>
  <%= f.text_field :hd_channels %>

  <%= f.label 'HD channels list (comma separated)' %>
  <%= f.text_field :hd_channels_list %>
  </div>
  <div>
    <%= f.fields_for :bundle_equipments do |builder| %>
      <%= render 'bundle_equipment_fields', f: builder %>
    <% end %>
    <!-- <p><%#= link_to_add_fields "Add Equipment", f, :bundle_equipments %></p> -->
  </div>
</fieldset>

app/views/deals/_cable_attribute.html.erb
<fieldset id="cable-attributes" style="display:none;">
  <h4>Cable/TV Deal Attributes</h4>
  <table class="form-data">
    <tr>
      <td>
      <div>Free channels<span class="mandat">*</span></div>
      <%= f.text_field :free_channels, :id=>'cable-free-channels' %>
      </td>
      <td>
      <%= f.label 'Free channels list (comma separated)' %>
      <%= f.text_field :free_channels_list %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.label :premium_channels %>
      <%= f.text_field :premium_channels %>
      </td>
      <td>
      <%= f.label 'Premium channels list (comma separated)' %>
      <%= f.text_field :premium_channels_list %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.label :hd_channels %>
      <%= f.text_field :hd_channels %>
      </td>
      <td>
      <%= f.label 'HD channels list (comma separated)' %>
      <%= f.text_field :hd_channels_list %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= f.fields_for :cable_equipments do |builder| %>
          <%= render 'cable_equipment_fields', f: builder %>
        <% end %>
      </td>
    </tr>
    <tr>
     <!--  <p><td colspan="2"><%#= link_to_add_fields "Add Equipment", f, :cable_equipments %></td></p> -->
    </tr>
  </table>
</fieldset>

app/views/deals/_cellphone_attribute.html.erb
<table width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <fieldset id="cellphone-attributes" style="display:none;">
        <h4>Cellphone Deal Attributes</h4>
        <table class="form-data">
          <tr>
            <td width="50%">
              <%= f.label :no_of_lines %>
              <%= f.text_field :no_of_lines %>
            </td>
            <td width="50%">
              <%= f.label :price_per_line %>
              <%= f.text_field :price_per_line %>
            </td>
          </tr>
          <tr>
            <td>
            <div><b>Talk &amp; Text</b></div><br/>
            <div>Domestic Call Minutes<span class="mandat">*</span></div>
            <div><input type='checkbox' id='cellphone_domestic_unlimited'><span> Unlimited</span></div>
            <%= f.text_field :domestic_call_minutes, :id=>'cellphone-domestic-call-minutes' %>
            </td>
            <td valign="bottom">
            <%= f.label :domestic_text %>
            <%= f.text_field :domestic_text %>
            </td>
          </tr>
          <tr>
            <td>
            <%= f.label :international_call_minutes %>
            <div><input type='checkbox' id='cellphone_international_unlimited'><span> Unlimited</span></div>
            <%= f.text_field :international_call_minutes,:id=>'cellphone-international-call-minutes' %>
            </td>
            <td valign="bottom">
            <%= f.label :international_text %>
            <%= f.text_field :international_text %>
            </td>
          </tr>
          <tr>
            <td><div><b>Data Plan</b></div></td>
          </tr>
          <tr>   
            <td>
            <%= f.label :data_plan %>
            <%= f.text_field :data_plan %>
            </td>
            <td>
              <%= f.label :data_plan_price %>
              <%= f.text_field :data_plan_price %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :additional_data %>
              <%= f.text_field :additional_data %>
            </td>
            <td>
              <%= f.label :additional_data_price %>
              <%= f.text_field :additional_data_price %>
            </td>
          </tr>
          <tr>
            <td>
              <div><%= f.check_box :rollover_data %> Rollover data </div>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <%= f.fields_for :cellphone_equipments do |builder| %>
                <%= render 'cellphone_equipment_fields', f: builder %>
              <% end %>
            </td>
          </tr>
          <tr>
            <!-- <p><td colspan="2"><%#= link_to_add_fields "Add Equipment", f, :cellphone_equipments %></td></p> -->
          </tr>
        </table>
      </fieldset>
    </td>
  </tr>
</table>

app/views/deals/_cellphone_equipment.html.erb
<%= f.fields_for :cellphone_equipments do |b_form| %>
  <tr>
    <td>
      <b>Equipments</b>
    </td>
  </tr>
  <tr>
    <td>
      <%= b_form.label :model %>
      <%= b_form.text_field :model %>
    </td>
    <td>
      <%= b_form.label :make %>
      <%= b_form.text_field :make %>
    </td>
  </tr>
  <tr>
    <td>
      <%= b_form.label :memory %>
      <%= b_form.text_field :memory %>
    </td>
    <td>
      <%= b_form.label :price %>
      <%= b_form.text_field :price %>
    </td>
  </tr>
  <tr>
    <td>
      <%= b_form.label :installation %>
      <%= b_form.text_field :installation %>
    </td>
    <td>
      <%= b_form.label :activation %>
      <%= b_form.text_field :activation %>
    </td>
  </tr>
<% end %>

app/views/deals/_cellphone_equipment_fields.html.erb
<%#= f.fields_for :cellphone_equipments do |f| %>
<table width="100%" cellpadding="0" cellspacing="0" border:none;>
  <tr>
    <td>
      <b>Equipments</b>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :model %>
      <%= f.text_field :model %>
    </td>
    <td>
      <%= f.label :make %>
      <%= f.text_field :make %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :memory %>
      <%= f.text_field :memory %>
    </td>
    <td>
      <%= f.label :price %>
      <%= f.text_field :price %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :installation %>
      <%= f.text_field :installation %>
    </td>
    <td>
      <%= f.label :activation %>
      <%= f.text_field :activation %>
    </td>
  </tr>
  <!-- <tr><td>
   <%#= f.hidden_field :_destroy %>
  <%#= link_to "Remove", '#', class: "remove_fields" %>
</td> -->
</tr>
</table>
<%# end %>

app/views/deals/_internet_attribute.html.erb
<fieldset id="internet-attributes" style="display:none;">
  <h4>Internet Deal Attributes</h4>

  <table class="form-data">
    <tr>
      <td>
      <div>Downloads (mbps)<span class="mandat">*</span></div>
      <%= f.text_field :download, :id=>'internet-download' %>
      </td>
      <td>
      <%= f.label 'Upload (mbps)' %>
      <%= f.text_field :upload %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.label :data %>
      <%= f.text_field :data %>
      </td>
      <td>
      <%= f.label :email %>
      <%= f.text_field :email %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.label :online_storage %>
      <%= f.text_field :online_storage %>
      </td>
      <td>
      <%= f.label :static_ip %>
      <%= f.text_field :static_ip %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= f.fields_for :internet_equipments do |builder| %>
          <%= render 'internet_equipment_fields', f: builder %>
        <% end %>
      </td>
    </tr>
    <tr>
      <!-- <p><td colspan="2"><%#= link_to_add_fields "Add Equipment", f, :internet_equipments %></td></p> -->
    </tr>
  </table>
</fieldset>

app/views/deals/index.html.erb
<table cellpadding='0' cellspacing='0' class='tabbed' height='100%' width='100%'>
  <tr>
    <td class='main' id='main' valign='top'>
      <div class='title_tools'>
        <% if current_user.is_super_admin? %>
            <%= link_to "Add New Deal", new_deal_path %>
        <% end %>
      </div>

      <div class='title'>
        <span id='title'>Deals</span>
      </div>
      <div id="service_deals" class="list">
        <div>
          <h6>Import from CSV</h6>
          <%= form_tag import_deals_path, multipart: true do %>
              <%= file_field_tag :file %>
              <%= submit_tag "Import CSV" %>
          <% end %><br/>
        </div>
        <table id="service_deals_list" class="datatable" cellpadding='0' cellspacing='0' border='1'>
          <thead>
          <tr>
            <th>ID</th>
            <th><strong>Category</strong></th>
            <th><strong>Provider</strong></th>
            <th><strong>Title</strong></th>
            <th><strong>Price</strong></th>
            <th><strong>Zipcodes</strong></th>
            <th><strong>Is Nationwide?</strong></th>
            <th><strong>Deal Type</strong></th>
            <th><strong>Start Date</strong></th>
            <th><strong>End Date</strong></th>
            <th><strong>Is Active?</strong></th>
            
            <th><strong>Is Sponsored?</strong></th>
            <th><strong>Edit</strong></th>
          </tr>
          </thead>
          <tbody>
          <% @deals.each do |s_deal| %>
              <% if can? :read, s_deal %>
                  <tr>
                    <td><%= s_deal.id %></td>
                    <td><%= s_deal.service_category.name %></td>
                    <td><%= s_deal.service_provider.name %></td>
                    <td><%= s_deal.title %></td>
                    <td><%= s_deal.price %></td>
                    <td></td>
                    <td><%= s_deal.is_nationwide %></td>
                    <td><%= s_deal.deal_type %></td>
                    <td><%= s_deal.start_date %></td>
                    <td><%= s_deal.end_date %></td>
                    <td><%= s_deal.is_active %></td>
                    <td><%= s_deal.is_sponsored %></td>
                    <td><%= (link_to 'Edit', edit_deal_path(s_deal)) if can? :manage, s_deal %> |
                      <%= (link_to "Delete", s_deal, method: :delete, data: { confirm: "Are you sure?" }) if can? :manage, s_deal %> |
                      <%= (link_to 'Add Equipment', new_deal_equipment_path(:deal_id => s_deal.id)) if can? :manage, s_deal %> |
                      <%= (link_to 'Add Attributes', new_deal_attribute_path(:deal_id => s_deal.id)) if can? :manage, s_deal %>
                    </td>
                  </tr>
              <% end %>
          <% end %>
          <div class="digg_pagination">
            <%= will_paginate @deals %>
          </div>
          </tbody>
        </table>
        <p>
          Download:
          <%= link_to "CSV", deals_path(format: "csv") %>
          <%#= link_to "Excel", service_categories_path(format: "xls") %>
        </p>
      </div>
    </td>
  </tr>
</table>      