config/routes.rb
require 'api'
Rails.application.routes.draw do
  devise_for :app_users, skip: [:sessions, :passwords, :registrations]
# root to: "home#index"
match  'blog' => 'website/home#blog', :via => :get
  get  '*a.txt', :to => 'website/errors#routing'


  namespace :api do
    namespace :v1 do
      devise_scope :app_user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      match 'service_categories' => 'service_categories#index', :via => :get
      match 'service_preferences' => 'service_preferences#create', :via => :post
      match 'service_preferences/send_ios_notification' => 'service_preferences#send_ios_notification', :via => :get
      match 'notifications' => 'notifications#create', :via => :post
      match 'get_notification' => 'notifications#fetch_notification', :via => :get
      match 'app_users' => 'app_users#create', :via => :post
      match 'update_user' => 'app_users#update_app_user', :via => :post
      match 'service_providers' => 'service_providers#get_service_providers', :via => :get
      match 'device_details' => 'device_tracker#add_devise_details', :via => :post
      match 'destroy_session' => 'device_tracker#destroy_session', :via => :post
      match 'get_preferences' => 'service_preferences#fetch_service_preferences', :via => :get
      match 'deselect_prference' => 'service_preferences#deselect_service_preference', :via => [:delete,:post]
      match 'get_states' => 'orders#get_states', :via => :get
      match 'get_cities' => 'orders#get_cities', :via => :get
      match 'primary_information' => "app_users#primary_information", :via => :get
      match 'cellphone_equipments' => "deals#cellphone_equipments", :via => :get
      match 'customisable_deals' => "deals#customisable_deals", :via => :get
      match 'customisable_deal_deatail' => "deals#customisable_deal_deatail", :via => :get
      match 'channel_customisable_deals' => "deals#channel_customisable_deals", :via => :get
      match 'cellphone_details' => "deals#cellphone_details", :via => :get
      match 'service_deal_config' => "deals#service_deal_config", :via => :get
      match 'password_complicated_setting' => "deals#password_complicated_setting", :via => :get
       match 'compare_deals' => "deals#compare_deals", :via => :get


      resources :dashboards do
        post 'dashboards' => 'dashboards#index'
      end
      resources :deals do
        get 'deals' => 'deals#index'
      end
      match 'app_user' => 'app_users#get_app_user', :via => :get
      match 'you_save' => 'app_users#you_save', :via => :get
      match 'service_preferences' => 'service_preferences#get_service_preferences', :via => :get
      match 'forget_password' => 'app_users#recover_password', :via => :post
      match 'comment_ratings' => 'comment_ratings#create', :via => :post
      match 'comment_ratings' => 'comment_ratings#index', :via => :get
      match 'referral_tracking' => 'referral_infos#create', :via => :post
      match 'get_category_deals' => 'dashboards#category_deals', :via => :get
      match 'subscribed_deals' => 'subscribe_deals#subscription_info', :via => :post
      match 'orders' => 'orders#create', :via => :post
      match 'get_orders' => 'orders#get_orders', :via => :get
      match 'my_orders' => 'orders#my_orders', :via => :get
      match 'get_order_address' => 'orders#get_order_address', :via => :get
      match 'get_gifts' => 'gifts#get_gifts', :via => :get
      match 'account_referrals' => 'account_referrals#create', :via => :post
      match 'referral_code' => 'app_users#my_referral_code', :via => :get
      match 'my_earnings' => 'app_users#referrals_and_gifts', :via => :get
      match 'cashout' => 'cashout_infos#create', :via => :post
      match 'refer_contact' => 'app_users#refer_contact', :via => :post
      match 'validate_business_name' => 'dashboards#validate_business_name', :via => :post
      match 'get_deal_channels' => 'deals#get_deal_channels', :via => :get
      match 'get_channel_details' => 'deals#get_channel_details', :via => :get
      match 'get_estimated_bandwidth' => 'deals#get_estimated_bandwidth', :via => :post
      match 'verify_user'=>"app_users#verify_user", :via => :get
      match 'deal_details'=>"deals#fetch_deal_details", :via => :get
      match 'dynamic_label_for_service_provider'=>"dashboards#dynamic_label_for_service_provider", :via => :get
      match 'get_rewards' => 'gifts#get_rewards', :via => :get
      resources :orders do
        collection do
          post :fetch_user_and_deal_details
          post :my_order_details
          post :validate_business_name
        end
      end

    end
  end

  #resources :service_categories do
  #  collection { post :import }
  #end
  get "/proxy_verify"=>"website/app_users#proxy_verify"
  match "/edit_addresses" => "website/app_users#edit_addresses", :via => [:post]
  match "/set_default_address" => "website/app_users#set_default_address", :via => [:post]
  match "/delete_address" => "website/app_users#delete_address", :via => [:post]
  match "/edit_or_change_service_preferences" => "api/v1/service_preferences#create", :via => :post
  get "/tnc" =>"website/home#tnc"
  get "/contact_us" =>"website/home#contact_us"
  get "/about_us" =>"website/home#about_us"
  get "/privacy_policy" =>"website/home#privacy_policy"

  #
  # if Socket.gethostname=="servicedlz-Virtual-Machine"
  # root to: "home#index"
  # else
  root to: "website/home#index"
  # end

  devise_for :users
  resources :users do
    member do
      get :edit_password
      get :unlock
      put :update_password
    end
    collection do
      get :reset_password
      post :set_reset_password
    end
  end
  get "/calculate_bandwidth" => "website/home#calculate_bandwidth"
  get "/get_deals_from_first_page" =>"website/home#get_deals_from_first_page"
  get '/get_user_addresses'=> "website/app_users#user_addresses"
  get '/get_business_user_addresses'=> "website/app_users#business_user_addresses"
  get "/extra_service_deal" => 'extra_services#extra_service_deal'

  get 'deals/get_service_providers'=>'deals#get_service_providers'
  get "/searchzip" => "deals#searchzip"
  get "/verify_email"=>"website/app_users#verify_email"
  resources :deals do
    post 'import', on: :collection
  end
  resources :service_categories do
    post 'import', on: :collection
  end
  resources :app_users
  resources :service_preferences
  resources :notifications
  resources :service_providers do
    post 'import', on: :collection
  end
  resources :advertisements
  #resources :comments
  #resources :ratings
  resources :bulk_notifications
  resources :comment_ratings
  resources :referral_infos
  resources :internet_service_preferences
  resources :cable_service_preferences
  resources :telephone_service_preferences
  resources :cellphone_service_preferences
  resources :bundle_service_preferences
  resources :subscribe_deals
  resources :trending_deals
  resources :zipcodes do
    post 'import', on: :collection
  end
  resources :orders
  resources :gifts
  resources :user_gifts
  resources :channels
  resources :channel_packages


  get 'service_dealz' => 'website/home#index'
  get 'service_deals' => 'website/home#index'
  get 'website' => 'website/home#index'
  namespace :website do
    resources :home do
      collection do
        get :deals
        get :compare_deals
        get :deal_details
        get :more_deal_details
        get :set_zipcode_and_usertype
        get :contact_us
        get :about_us
        get :our_providers
        get :coming_soon
        get :tnc
      end
    end

    resources :app_users do
      collection do
        get :check_user_email_ajax
        get :check_user_credential
        get :signout
        post :signin
        get :checkout
        get :profile
        get :order_history
        post :preferences
        get :order
        get :order_detail
        post :create_order
        post :contact_us
        get :forget_password
        get :edit_password
        post :update_password
        get :order_attributes
        get :order_extra_services
        get :order_equipment_data
        get :order_channel_packages
        get :order_cable_equipments
      end
    end
  end

  resources :referral_gift_amounts
  resources :service_provider_checklists do
    post 'import', on: :collection
  end
  resources :deal_equipments
  resources :deal_attributes
  resources :deal_extra_services
  resources :equipment_colors
  resources :cellphone_details
  resources :extra_services

  get  '*a', :to => 'website/errors#routing'


end

app/models/app_user.rb
class AppUser < ActiveRecord::Base
  ##include Encrypt
  #before_save :encrypt_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :trackable
  has_many :service_preferences, dependent: :destroy
  has_one :notification, dependent: :destroy
  has_many :comment_ratings, dependent: :destroy
  has_many :subscribe_deals, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :user_gifts,:dependent => :destroy
  has_many :gifts, through: :user_gifts
  has_many :referrals, :class_name => "AccountReferral", :foreign_key => "referral_id",dependent: :destroy
  has_one :referrer, :class_name => "AccountReferral", :foreign_key => "referrer_id",dependent: :destroy
  has_many :app_user_addresses, dependent: :destroy
  has_many :business_app_users, dependent: :destroy
  has_many :refer_contact_details
  #has_many :comments, dependent: :destroy
  #has_many :ratings, dependent: :destroy
  mount_uploader :avatar, ImageUploader

  # before_save :encode_data
  ##before_save :encrypt_data
  validates :email, :presence => true, :uniqueness => true
  # validates :password, :presence => true, :confirmation => true, :on => :create

  ## user type
  RESIDENCE = 'residence'
  BUSINESS = 'business'

  PRIMARY_ID = ["Driving License" , "Passport","State ID Card", "US Military Card", "US Military Department ID Card", "US Coast Guard Merchant Mariner Card", "EAD" ]
  SECONDARY_ID = ["Major Credit Card" , "Driving License","Passport"," State ID Card", "US Military Card", "US Military Department ID Card", "US Coast Guard Merchant Mariner Card", "EAD", "Birth Certificate" ]
  USER_TYPES = [RESIDENCE,BUSINESS]
  # STATES = Statelist.all.pluck(:state).uniq
  STATES =Statelist.all.order('state ASC').pluck(:state).uniq


   def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while AppUser.exists?(column => self[column])
  end

  def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  AppUserMailer.recover_password_email(self).deliver
end


  def encrypt_data
    ##self.zip = encode_data({'data' => self.zip}) if self.zip.present?
  end

  def avatar_url
    avatar.url
  end

  def as_json(opts={})
    json = super(opts)
    Hash[*json.map{|k, v| [k, v || ""]}.flatten]
  end

  def self.encrypt(password)
    Digest::SHA1.hexdigest("#{password}")
  end

  def self.authenticate(email, password)
    user = self.select('id,first_name,last_name,email,encrypted_password,active,zip,user_type').where(:email => email).first
    if user.present? && password.present?
      user.valid_password?(password) ? user : nil
    else
      nil
    end
  end


  def self.get_addresses(params)
    app_user = AppUser.find_by_id(params[:id])
    addresses_array = []
    addresses = app_user.business_app_users.last.business.business_addresses if app_user.user_type == AppUser::BUSINESS
    addresses = app_user.app_user_addresses if app_user.user_type == AppUser::RESIDENCE
    addresses_array << addresses.where(address_type: BusinessAddress::BILLING_ADDRESS).order('updated_at DESC').first
    addresses_array << addresses.where(address_type: BusinessAddress::SHIPPING_ADDRESS).order('updated_at DESC').first
    addresses_array << addresses.where(address_type: BusinessAddress::BRANCH_ADDRESS).order('updated_at DESC').first
  end


  def self.update_app_user(params,app_user_id,order = nil)
    app_user = self.where(:id => app_user_id).first
    params[:app_user].each do |key,value|
      app_user[key] = value unless key == 'email'
    end
    if order.present?
      app_user.primary_id = order.primary_id
      app_user.secondary_id = order.secondary_id
      app_user.primary_id_number = order.primary_id_number
      app_user.secondary_id_number = order.secondary_id_number
    end
    if app_user.save!
      app_user
    else
      app_user
    end
  end

end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController
	def index
		@app_users = AppUser.paginate(:page => params[:page], :per_page => 20).order("id DESC")
		respond_to do |format|
      format.html
      #format.xls # { send_data @products.to_csv(col_sep: "\t") }
      format.csv {
        csv_string = CSV.generate do |csv|
          # header row
          csv <<
          [	"ID",
          	"First Name",
          	"Last Name",
          	"Email",
          	"Address",
          	"State",
          	"City",
          	"Zip",
          	"Avatar",
          	"Device Flag",
          	"Sign in Count",
          	"Encrypted Password",
          	"Password",
          	"Device Id",
          	"ResetPassword Token",
          	"ResetPasswordSent At",
          	"RememberCreated At",
          	"CurrentSignIn At",
          	"LastSignIn At",
          	"CurrentSignIn IP",
          	"LastSignIn IP",
          	"Created At",
          	"Updated At",
          ]

          # data rows
          AppUser.all.order("id ASC").each do |app_user|
            csv <<
            [ app_user.id,
              app_user.first_name,
              app_user.last_name,
              app_user.email,
              app_user.address,
              app_user.state,
              app_user.city,
              app_user.zip,
              app_user.avatar_url,
              app_user.device_flag,
              app_user.sign_in_count,
              app_user.encrypted_password,
              app_user.unhashed_password,
              app_user.gcm_id,
              app_user.reset_password_token,
              app_user.reset_password_sent_at,
              app_user.remember_created_at,
              app_user.current_sign_in_at,
              app_user.last_sign_in_at,
              app_user.current_sign_in_ip,
              app_user.last_sign_in_ip,
              app_user.created_at,
              app_user.updated_at
            ]
          end
        end
        # send it to the browser
        send_data csv_string,
          :type => 'text/csv; charset=iso-8859-1; header=present',
          :disposition => "attachment; filename=app_users.csv"
      }
    end
	end
	def new
		@app_user = AppUser.new
	end
	def edit
		@app_user = AppUser.find(params[:id])
	end
	def create
		 
		@app_user = AppUser.new(app_user_params)
		respond_to do |format|
			if @app_user.save
				format.html { redirect_to app_users_path, :notice => 'Successfully created.' }
				format.xml { render :xml => app_user, :status => :created, :app_user => @app_user }
				format.html { render :action => "new" }
				format.xml { render :xml => app_user.errors, :status => :unprocessable_entity }
			end
		end
	end

	def update
		@app_user = AppUser.find(params[:id])
    	respond_to do |format|
      		if @app_user.update_attributes(app_user_params)
        		format.html { redirect_to app_users_path, notice: 'You have successfully updated a user.' }
        		format.xml  { render :xml => @app_user, :status => :created, :user => @app_user }
      		else
        		format.html { render :edit }
        		format.json { render json: @app_user.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  	def destroy
    	@app_user = AppUser.find(params[:id])
    	respond_to do |format|
      		if @app_user.destroy
        		format.html { redirect_to app_users_path, :notice => 'You have successfully removed a user' }
        		format.xml  { render :xml => @app_user, :status => :created, :app_user => @app_user }
      		end
    	end
   end

	private
	def app_user_params
		params.require(:app_user).permit(:first_name, :last_name, :avatar, :email, :state, :city, :zip, :password, :address, :unhashed_password, :active, :gcm_id, :device_flag,:refer_status)
	end
end

app/controllers/website/errors_controller.rb
class Website::ErrorsController < ApplicationController
  def routing
  end
end

app/helpers/website/errors_helper.rb
module Website::ErrorsHelper
end

app/views/website/app_users/_my_earning.html.erb
FVfv

app/views/website/app_users/_order_history.html.erb
<div id="Order" class="order-tab tab-pane fade" role="tabpanel">
  <div class="scroller_order">
    <div class="border-radius-bg">
      <ul class="nav nav-pills" id="orderMenu">
        <li class="active"><a data-toggle="tab" id="home" href="#home" aria-expanded="false">All order</a></li>
         <% ServiceCategory.first(5).each do |service_category| %>
            <li class=""><a href="#<%= service_category.name.downcase %>" id="<%= service_category.name.downcase %>" data-toggle="tab" aria-expanded="false">
               <%=service_category.name %></a></li>
        <% end %>
      </ul>
      <div class="tab-content" id="order_list">


      </div>
    </div>
  </div>
</div>
<script>
    $("#orderMenu").children('li').click( function() {
        var order_category_id = $(this).children('a').attr('id');
        request = void 0;
        request = $.ajax({
            type:'GET',
            url: "<%= order_history_website_app_users_path%>",
            data: {id: order_category_id}
        });
    });
    $("#order-tab").click( function() {
        request = void 0;
        request = $.ajax({
            type:'GET',
            url: "<%= order_history_website_app_users_path%>",
            data: {id: "home"}
        });
    });
</script>

app/views/website/app_users/_order_list.html.erb
<% if @order_history.present? %>
    <div id="home" class="tab-pane fade active in">
      <div class="row desc_heading">
        <div class="col-xs-2"> <h5>Description</h5> </div>
        <div class="col-xs-2"> <h5>Order date</h5> </div>
            <div class="col-xs-2"> <h5>Status</h5> </div>

            <!-- <div class="col-xs-2"> <h5>Price</h5>   </div> -->
            <div class="col-xs-2"> <h5>Order No.</h5> </div>
            <div class="col-xs-2"> <h5>Order Total</h5> </div>

      </div>
      <% @order_history.each do |order| %>
          <div class="row desc_cont">
            <div class="col-xs-2">
              <span class="img_border">
                <% deal = Deal.find_by_id(order.order_items.first.deal_id) %>

                <%if display_logo_permission(deal.service_provider_id,deal.deal_type)%>
                  <img src="<%= display_logo_permission(deal.service_provider_id,deal.deal_type)%>" alt="Service Provider Logo" class="img-responsive">
                <%else%>
                  <%= image_tag("#{deal.image}", :alt => "logo") %>
                <% end %>
                </span>
              <p class="para_3"><%= deal.title %></p>
            </div>
                <div class="col-xs-2"> <p><%=order.created_at.strftime("%m/%d/%y")%></div>
                <div class="col-xs-2"> <p><span class="panding"><%= order.status %></span></p> </div>
                <!-- <div class="col-xs-2"> <p><%#s= order.order_items.first.deal_price%></p>   </div> -->
                <div class="col-xs-2"> <p><%= order.order_number%></p> </div>
                <div class="col-xs-2"> <p>$<%="%.2f" %  order.order_items.first.effective_price if order.order_items.first.effective_price.present? %></p> </div>
                <div class="col-xs-2"> <p><%= link_to "Order Detail",  order_detail_website_app_users_path(order_id: order.id)%><br /></p> </div>

          </div>
      <% end %>
    </div>
<%elsif%>
    </br><div style="color:red; padding-left:200px">There are no Orders in this category.</div>
<% end %>

app/views/website/app_users/_user_preferences.html.erb
<div id="Preference" class="prefrence-tab tab-pane fade" role="tabpanel">
  <%#= form_for(Notification.new, :url => @notifications, id: 'notification-form') do |f| %>
  <%= form_tag preferences_website_app_users_path(@app_user), method: :post do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <h4>Deal Notification</h4>
  <div class="receive-notification">Receive notification before contract expire</div>
    <div class="row">

      <div class="col-md-12 details-zip">
        <%#= label_tag :recieve_notification, "Yes", :value => "true"  %>
        <%#= radio_button_tag 'notification[recieve_notification]', true,@app_user.notification.try(:recieve_notification) %>


        <div class="col-xs-2 col-md-2 radio_inline">
                      <label>
                        <input type="radio" name="optionsRadios" id="residence" value="low">
                        <i class="fa fa-circle-o fa-2x"></i><i class="fa fa-dot-circle-o fa-2x"></i> <span> Yes</span> </label>
                    </div>

                    <div class="col-xs-2 col-md-2 radio_inline">
                                  <label>
                                    <input type="radio" name="optionsRadios" id="residence" value="low">
                                    <i class="fa fa-circle-o fa-2x"></i><i class="fa fa-dot-circle-o fa-2x"></i> <span> No</span> </label>
                                </div>

        <%#= label_tag :recieve_notification, "No", :value => "false" %>
        <%#= radio_button_tag 'notification[recieve_notification]', false%>



      </div>


      <div class="col-md-12"><div class="form-group  col-md-4 mgt20">
        <label>First Notification</label>
        <%= text_field_tag('notification[day]' ,@app_user.notification.try(:day),:class => 'form-control',:placeholder => 'Day') %>
      </div>

        <div class="form-group col-md-4 mgt20">
          <div>
            <label>Last Notification</label>
            <%= select_tag('notification[repeat_notification_frequency]',options_for_select(["Weekly" , "Bi-Weekly","Daily" ],selected: @app_user.notification.try(:repeat_notification_frequency)),:class => 'form-control',) %>
          </div>
        </div></div>


      <div class="col-md-12">
        <!-- <input type="checkbox" id="checkbox8a"> -->
          <%#=check_box_tag('notification[recieve_trending_deals]', nil,0,:class=>"recievecallcbox") %>
        <%#= f.check_box :recieve_trending_deals%>


        <div class="checkbox checkbox-info">
            <!--<input id="" type="checkbox" class="provider_checkbox">
            -->

            <input type="checkbox" name="AT&amp;T" id="1" value="1" class="provider_checkbox">
            <label for="1"> <span>Receive Trending Deals and Special offers  </span> </label>
          </div>





      </div>




      <%if @app_user.notification.present? and @app_user.notification.recieve_trending_deals%>
      <script>$(".recievecallcbox:checked").prop("checked",true)</script>
      <%else%>
        <script>$(".recievecallcbox:checked").attr("checked",false)</script>
      <%end%>


      <div class="col-md-12">
        <!-- <input type="checkbox" id="checkbox8b"> -->
        <%#= check_box_tag('notification[receive_call]',nil,0,:class=>"recievecallcbox") %>
         <!-- <%#= f.check_box :receive_call%><span> Call and Receive calls </span> -->
         <%#if @app_user.notification.present? and @app_user.notification.receive_call%>
         <!-- <script>$(".recievecallcbox:checked").prop("checked",true)</script> -->
         <%#else%>
           <!-- <script>$(".recievecallcbox:checked").attr("checked",false)</script> -->
         <%#end%>



                  <div class="checkbox checkbox-info">
                      <!--<input id="" type="checkbox" class="provider_checkbox">
                      -->

                      <input type="checkbox" name="AT&amp;T" id="2" value="2" class="provider_checkbox">
                      <label for="2"> <span> Call and Receive calls  </span> </label>
                    </div>


      </div>
    </div>


    <h4>Ratings</h4>
    <div class="row">

      <div class="col-md-12"><div class="form-group  col-md-4 ">
        <label>Minimum Service Provider Rating</label>
        <%= select_tag('notification[min_service_provider_rating]',options_for_select([["☆ ☆ ☆ ☆ ☆","5"], ["☆ ☆ ☆ ☆","4"],["☆ ☆ ☆","3"],["☆ ☆","2"],["☆","1" ]],selected: @app_user.notification.try(:min_service_provider_rating)),:class => 'form-control',) %>
      </div>

        <div class="form-group col-md-4">
          <div>
            <label>Minimum Deal Rating</label>
            <%= select_tag('notification[min_deal_rating]',options_for_select([["☆ ☆ ☆ ☆ ☆","5"], ["☆ ☆ ☆ ☆","4"],["☆ ☆ ☆","3"],["☆ ☆","2"],["☆","1" ]],selected: @app_user.notification.try(:min_deal_rating)),:class => 'form-control',) %>
          </div>
        </div></div>


      <div class="col-md-12 margin_checkbox">
        <h4>Communications Permissions</h4>
          <%#= check_box_tag('notification[receive_email]',nil,0, :class=>"recieve_emailcbox") %>
          <!-- <%if @app_user.notification.present? and @app_user.notification.receive_email%> -->
          <!-- <script>$(".recieve_emailcbox:checked").prop("checked",true)</script> -->
          <%#else%>
            <!-- <script>$(".recieve_emailcbox:checked").attr("checked",false)</script> -->
          <!-- <%end%> -->

          <div class="checkbox checkbox-info">
              <!--<input id="" type="checkbox" class="provider_checkbox">
              -->

              <input type="checkbox" name="AT&amp;T" id="4" value="2" class="provider_checkbox">
              <label for="4"> <span> Receive emails </span> </label>
            </div>


      </div>

      <div class="col-md-12">
          <%#= check_box_tag('notification[receive_text]',nil,0,:class=>"recieve_textcbox") %>
          <!-- <%if @app_user.notification.present? and @app_user.notification.receive_text%> -->
          <!-- <script>$(".recieve_textcbox:checked").prop("checked",true)</script> -->
          <%#else%>
            <!-- <script>$(".recieve_textcbox:checked").attr("checked",false)</script> -->
          <!-- <%end%> -->



           <div class="checkbox checkbox-info">
               <!--<input id="" type="checkbox" class="provider_checkbox">
               -->

               <input type="checkbox" name="AT&amp;T" id="5" value="5" class="provider_checkbox">
               <label for="5"> <span> Receive Texts  </span> </label>
             </div>


      </div>

      <div class="col-sm-6">
        <div>
          <%= submit_tag('Send',:class => 'btn theme-btn') %>
          <%#= f.submit "Send",class:"btn btn-info",id: 'notification-submit' %>
        </div>



        <!-- <button id="Send" name="Send" class="btn btn-info">Save</button> -->
      </div>
    </div>
<%end%>

</div>

app/views/website/app_users/edit_password.html.erb
<section class="bandwidth-banner ">
  <div class="container text-center">
    <h3>Reset Password</h3>
  </div>
</section>

<section class="bandwidth-calc account_page_height">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        
        <p>Please enter a new pasword for your ServiceDealz.com account </p>
      </div>
     


<div class="col-md-12  reset-password">
   <div class="col-md-6">
<%= form_for @app_user, :url => update_password_website_app_users_path(id: params[:id]), :method => "post" do |f| %>
  <% if @app_user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="field"> -->
     <div class="usage-type"> <strong>New Password</strong>
    <%= f.password_field :password, :class=>"form-control"  %>
  </div>
  <!-- <div class="field"> -->
    <div class="usage-type"> <strong>Confirm Password</strong>
    <%= f.password_field :password_confirmation , :class=>"form-control"%>
  </div>
</div>
  <div class="col-md-12 actions"><%= f.submit "Update Password", :class=> "btn bandwidth-btn" %></div>
<% end %>


</div>
</div>
</section>

<!-- <div class="col-md-12  reset-password">
        
        <div class="col-md-6">
          
          <div class="usage-type"> <strong>Old Password</strong>
          
            
              <input class="form-control" placeholder="Enter new Password" type="text">
            
        
            
             </div>
             <div class="usage-type"> <strong>New Password</strong>
          
          
              <input class="form-control" placeholder="Enter new Password" type="text">
            
          
            
             </div>
        </div>
        <div class="col-md-12">
          <button  class="btn bandwidth-btn" type="button"> Save Changes</button>
        </div>
        
        
      </div>
 -->

app/views/website/app_users/order_history.js.erb
$("#order_list").html("<%= escape_javascript(render('order_list', locals: { order_history: @order_history } )) %>")