config/routes.rb
require 'api'
Rails.application.routes.draw do
  devise_for :app_users, skip: [:sessions, :passwords, :registrations]
# root to: "home#index"
match  'blog' => 'website/home#blog', :via => :get
  get  '*a.txt', :to => 'website/errors#routing'


  namespace :api do
    namespace :v1 do
      devise_scope :app_user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      match 'service_categories' => 'service_categories#index', :via => :get
      match 'service_preferences' => 'service_preferences#create', :via => :post
      match 'service_preferences/send_ios_notification' => 'service_preferences#send_ios_notification', :via => :get
      match 'notifications' => 'notifications#create', :via => :post
      match 'get_notification' => 'notifications#fetch_notification', :via => :get
      match 'app_users' => 'app_users#create', :via => :post
      match 'update_user' => 'app_users#update_app_user', :via => :post
      match 'service_providers' => 'service_providers#get_service_providers', :via => :get
      match 'device_details' => 'device_tracker#add_devise_details', :via => :post
      match 'destroy_session' => 'device_tracker#destroy_session', :via => :post
      match 'get_preferences' => 'service_preferences#fetch_service_preferences', :via => :get
      match 'deselect_prference' => 'service_preferences#deselect_service_preference', :via => [:delete,:post]
      match 'get_states' => 'orders#get_states', :via => :get
      match 'get_cities' => 'orders#get_cities', :via => :get
      match 'primary_information' => "app_users#primary_information", :via => :get
      match 'cellphone_equipments' => "deals#cellphone_equipments", :via => :get
      match 'customisable_deals' => "deals#customisable_deals", :via => :get
      match 'customisable_deal_deatail' => "deals#customisable_deal_deatail", :via => :get
      match 'channel_customisable_deals' => "deals#channel_customisable_deals", :via => :get
      match 'cellphone_details' => "deals#cellphone_details", :via => :get
      match 'service_deal_config' => "deals#service_deal_config", :via => :get
      match 'password_complicated_setting' => "deals#password_complicated_setting", :via => :get
       match 'compare_deals' => "deals#compare_deals", :via => :get


      resources :dashboards do
        post 'dashboards' => 'dashboards#index'
      end
      resources :deals do
        get 'deals' => 'deals#index'
      end
      match 'app_user' => 'app_users#get_app_user', :via => :get
      match 'you_save' => 'app_users#you_save', :via => :get
      match 'service_preferences' => 'service_preferences#get_service_preferences', :via => :get
      match 'forget_password' => 'app_users#recover_password', :via => :post
      match 'comment_ratings' => 'comment_ratings#create', :via => :post
      match 'comment_ratings' => 'comment_ratings#index', :via => :get
      match 'referral_tracking' => 'referral_infos#create', :via => :post
      match 'get_category_deals' => 'dashboards#category_deals', :via => :get
      match 'subscribed_deals' => 'subscribe_deals#subscription_info', :via => :post
      match 'orders' => 'orders#create', :via => :post
      match 'get_orders' => 'orders#get_orders', :via => :get
      match 'my_orders' => 'orders#my_orders', :via => :get
      match 'get_order_address' => 'orders#get_order_address', :via => :get
      match 'get_gifts' => 'gifts#get_gifts', :via => :get
      match 'account_referrals' => 'account_referrals#create', :via => :post
      match 'referral_code' => 'app_users#my_referral_code', :via => :get
      match 'my_earnings' => 'app_users#referrals_and_gifts', :via => :get
      match 'cashout' => 'cashout_infos#create', :via => :post
      match 'refer_contact' => 'app_users#refer_contact', :via => :post
      match 'validate_business_name' => 'dashboards#validate_business_name', :via => :post
      match 'get_deal_channels' => 'deals#get_deal_channels', :via => :get
      match 'get_channel_details' => 'deals#get_channel_details', :via => :get
      match 'get_estimated_bandwidth' => 'deals#get_estimated_bandwidth', :via => :post
      match 'verify_user'=>"app_users#verify_user", :via => :get
      match 'deal_details'=>"deals#fetch_deal_details", :via => :get
      match 'dynamic_label_for_service_provider'=>"dashboards#dynamic_label_for_service_provider", :via => :get
      match 'get_rewards' => 'gifts#get_rewards', :via => :get
      resources :orders do
        collection do
          post :fetch_user_and_deal_details
          post :my_order_details
          post :validate_business_name
        end
      end

    end
  end

  #resources :service_categories do
  #  collection { post :import }
  #end
  get "/proxy_verify"=>"website/app_users#proxy_verify"
  match "/edit_addresses" => "website/app_users#edit_addresses", :via => [:post]
  match "/set_default_address" => "website/app_users#set_default_address", :via => [:post]
  match "/delete_address" => "website/app_users#delete_address", :via => [:post]
  match "/edit_or_change_service_preferences" => "api/v1/service_preferences#create", :via => :post
  get "/tnc" =>"website/home#tnc"
  get "/contact_us" =>"website/home#contact_us"
  get "/about_us" =>"website/home#about_us"
  get "/privacy_policy" =>"website/home#privacy_policy"

  #
  # if Socket.gethostname=="servicedlz-Virtual-Machine"
  # root to: "home#index"
  # else
  root to: "website/home#index"
  # end

  devise_for :users
  resources :users do
    member do
      get :edit_password
      get :unlock
      put :update_password
    end
    collection do
      get :reset_password
      post :set_reset_password
    end
  end
  get "/calculate_bandwidth" => "website/home#calculate_bandwidth"
  get "/get_deals_from_first_page" =>"website/home#get_deals_from_first_page"
  get '/get_user_addresses'=> "website/app_users#user_addresses"
  get '/get_business_user_addresses'=> "website/app_users#business_user_addresses"
  get "/extra_service_deal" => 'extra_services#extra_service_deal'

  get 'deals/get_service_providers'=>'deals#get_service_providers'
  get "/searchzip" => "deals#searchzip"
  get "/verify_email"=>"website/app_users#verify_email"
  resources :deals do
    post 'import', on: :collection
  end
  resources :service_categories do
    post 'import', on: :collection
  end
  resources :app_users
  resources :service_preferences
  resources :notifications
  resources :service_providers do
    post 'import', on: :collection
  end
  resources :advertisements
  #resources :comments
  #resources :ratings
  resources :bulk_notifications
  resources :comment_ratings
  resources :referral_infos
  resources :internet_service_preferences
  resources :cable_service_preferences
  resources :telephone_service_preferences
  resources :cellphone_service_preferences
  resources :bundle_service_preferences
  resources :subscribe_deals
  resources :trending_deals
  resources :zipcodes do
    post 'import', on: :collection
  end
  resources :orders
  resources :gifts
  resources :user_gifts
  resources :channels
  resources :channel_packages


  get 'service_dealz' => 'website/home#index'
  get 'service_deals' => 'website/home#index'
  get 'website' => 'website/home#index'
  namespace :website do
    resources :home do
      collection do
        get :deals
        get :compare_deals
        get :deal_details
        get :more_deal_details
        get :set_zipcode_and_usertype
        get :contact_us
        get :about_us
        get :our_providers
        get :coming_soon
        get :tnc
      end
    end

    resources :app_users do
      collection do
        get :check_user_email_ajax
        get :check_user_credential
        get :signout
        post :signin
        get :checkout
        get :profile
        get :order_history
        post :preferences
        get :order
        get :order_detail
        post :create_order
        post :contact_us
        get :forget_password
        get :edit_password
        post :update_password
        get :order_attributes
        get :order_extra_services
        get :order_equipment_data
        get :order_channel_packages
        get :order_cable_equipments
      end
    end
  end

  resources :referral_gift_amounts
  resources :service_provider_checklists do
    post 'import', on: :collection
  end
  resources :deal_equipments
  resources :deal_attributes
  resources :deal_extra_services
  resources :equipment_colors
  resources :cellphone_details
  resources :extra_services

  get  '*a', :to => 'website/errors#routing'


end

app/models/bundle_service_preference.rb
class BundleServicePreference < ActiveRecord::Base
	belongs_to :service_preference
	def as_json(opts={})
    	json = super(opts)
    	Hash[*json.map{|k, v| [k, v || ""]}.flatten]
  	end
end

app/controllers/bundle_service_preferences_controller.rb
class BundleServicePreferencesController < ApplicationController
	
	def index
		@bundle_service_preferences = BundleServicePreference.all
    respond_to do |format|
      format.html
      #format.xls # { send_data @products.to_csv(col_sep: "\t") }
      format.csv {
        csv_string = CSV.generate do |csv|
          # header row
          csv << 
          [ "ID",   
            "ServicePreference ID", 
            "Bundle Combo",          
            "Upload Speed",
            "Download Speed",
            "Free Channels",
            "Premium Channels",
            "DomesticCall Minutes",
            "InternationalCall Minutes",
            "DomesticCall Unlimited",
            "InternationalCall Unlimited",
            "Data",
            "Data Speed",
            "Data Plan",
            "Created At",
            "Updated At",         
          ]  

          # data rows
          BundleServicePreference.all.order("id ASC").each do |bsp|
            csv << 
            [ bsp.id, 
              bsp.service_preference_id,                 
              bsp.bundle_combo,
              bsp.upload_speed,
              bsp.download_speed,
              bsp.free_channels,
              bsp.premium_channels,
              bsp.domestic_call_minutes,
              bsp.international_call_minutes,
              bsp.domestic_call_unlimited,
              bsp.international_call_unlimited,
              bsp.data,
              bsp.data_speed,
              bsp.data_plan,
              bsp.created_at,
              bsp.updated_at
            ]
          end               
        end 
        # send it to the browser
        send_data csv_string, 
          :type => 'text/csv; charset=iso-8859-1; header=present', 
          :disposition => "attachment; filename=bundle_service_preferences.csv" 
      }
    end
	end

  def edit
    @bundle_service_preference = BundleServicePreference.find(params[:id])
  end

  def update
    @bundle_service_preference = BundleServicePreference.find(params[:id])
    respond_to do |format|
      if @bundle_service_preference.update(bundle_service_preference_params)
        format.html { redirect_to bundle_service_preferences_path, notice: 'Successfully updated.' }
        format.xml  { render :xml => @bundle_service_preference, :status => :created, :bundle_service_preference => @bundle_service_preference }
      else
        format.html { render :edit }
        format.json { render json: @bundle_service_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @bundle_service_preference = BundleServicePreference.find(params[:id])
      respond_to do |format|
          if @bundle_service_preference.destroy
            format.html { redirect_to bundle_service_preferences_path, :notice => 'You have successfully removed a service preference' }
            format.xml  { render :xml => @bundle_service_preference, :status => :created, :bundle_service_preference => @bundle_service_preference }
          end
      end
  end

  private
  def bundle_service_preference_params
    params.require(:bundle_service_preference).permit(:service_preference_id, :upload_speed, :download_speed, :data, :free_channels, :premium_channels, :domestic_call_minutes, :international_call_minutes, :domestic_call_unlimited, :international_call_unlimited, :data_plan, :data_speed, :bundle_combo)
  end
end 

app/views/bundle_service_preferences/edit.html.erb
<table cellpadding='0' cellspacing='0' class='tabbed' height='100%' width='100%' >
  <tr> 
    <td class='main' id='main' valign='top'>

      <div class='title_tools'>
				<% if current_user.is_at_admin_level? %><%= link_to "View All Bundle Service Preferences", bundle_service_preferences_path %><% end %>
      </div>
      <div class='title'>
        <span id='title'>Update Bundle Service Preference</span>
      </div>
			<div class="small-6 large-centered columns">
				<%= form_for(@bundle_service_preference) do |f| %><br/>
				  <div><strong>Service Preference Id : </strong><br />
				  <%= f.text_field :service_preference_id, :readonly => true %></div>
				  <div><strong>Bundle Combo : </strong><br />
				  <%= f.text_field :bundle_combo %></div>
				  <div><strong>Upload Speed :</strong><br />
				  <%= f.text_field :upload_speed %></div>
				  <div><strong>Download Speed :</strong><br />
				  <%= f.text_field :download_speed %></div>
				  <div><strong>Data :</strong><br />
				  <%= f.text_field :data %></div>
				  <div><strong>Free Channels :</strong><br />
				  <%= f.text_field :free_channels %></div>
				  <div><strong>Premium Channels :</strong><br />
				  <%= f.text_field :premium_channels %></div>
				  <div><strong>Domestic Call Minutes :</strong><br />
				  <%= f.text_field :domestic_call_minutes %></div>
				  <div><strong>International Call Minutes :</strong><br />
				  <%= f.text_field :international_call_minutes %></div>
				  <div><strong>Data Plan :</strong><br />
				  <%= f.text_field :data_plan %></div>
				  <div><strong>Data Speed :</strong><br />
				  <%= f.text_field :data_speed %></div>
				  <div><%= f.check_box :domestic_call_unlimited %><strong>Domestic Call Unlimited ? </strong></div>
				  <div><%= f.check_box :international_call_unlimited %><strong>International Call Unlimited ? </strong></div>
				  <div><%= f.submit "Update" %></div>
				<% end %>
			</div>
    </td>
	</tr>
</table>

app/views/bundle_service_preferences/index.html.erb
<table cellpadding='0' cellspacing='0' class='tabbed' height='100%' width='100%'>
	<tr>
		<td class='main' id='main' valign='top'>
			<div class='title_tools'>
				<% if current_user.is_super_admin? %>
					<%#= link_to "Create New Service Preferences", new_service_preference_path %>
				<% end %>
			</div>

			<div id="users" class="list">
				<table id="users_list" class="datatable" cellpadding='0' cellspacing='0' border='1'>
					<thead>
						<tr>
							<th><strong>ID</strong></th>
							<th><strong>Service Preference Id</strong></th>
							<th><strong>Bundle Combo</strong></th>
							<th><strong>Upload Speed</strong></th>
							<th><strong>Download Speed</strong></th>
							<th><strong>Data</strong></th>
							<th><strong>Free Channels</strong></th>
							<th><strong>Premium Channels</strong></th>
							<th><strong>Domestic Call Minutes</strong></th>
							<th><strong>International Call Minutes</strong></th>
							<th><strong>Data Plan</strong></th>
							<th><strong>Data Speed</strong></th>
							<th><strong>Domestic Call Unlimited</strong></th>
							<th><strong>International Call Unlimited</strong></th>
							<th><strong>Action</strong></th>
						</tr>
					</thead>
					<tbody>
						<% @bundle_service_preferences.each do |bsp| %>
							<% if can? :read, bsp %>
								<tr>
									<td><%= bsp.id %></td>
									<td><%= bsp.service_preference_id %></td>
									<td><%= bsp.bundle_combo %></td>
									<td><%= bsp.upload_speed %></td>
									<td><%= bsp.download_speed %></td>
									<td><%= bsp.data %></td>
									<td><%= bsp.free_channels %></td>
									<td><%= bsp.premium_channels %></td>
									<td><%= bsp.domestic_call_minutes %></td>
									<td><%= bsp.international_call_minutes %></td>
									<td><%= bsp.data_plan %></td>
									<td><%= bsp.data_speed %></td>
									<td><%= bsp.domestic_call_unlimited %></td>
									<td><%= bsp.international_call_unlimited %></td>
									<td><%= (link_to 'Edit', edit_bundle_service_preference_path(bsp)) if can? :manage, bsp %> | <%= (link_to "Delete", bsp, method: :delete, data: { confirm: "You sure?" }) if can? :manage, bsp %></td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
				<p>
          Download:
          <%= link_to "CSV", bundle_service_preferences_path(format: "csv") %>
          <%#= link_to "Excel", service_categories_path(format: "xls") %>
        </p>

			</div>
		</td>
	</tr>
</table>